### PR TITLE
allow Symfony 7

### PR DESCRIPTION
**Pull request by tacman**

### CODE REVIEW

**Comment by SimonMellerin** [comment]
Hi,

Did you test this on an actual Symfony 7 project ?

**Comment by tacman** [comment]
No, in part because I can never remember how to install a version 6 bundle in a Symfony 7  project to test/develop it!   But I've found that if it works with 6.4 it's very likely to work with 7.0.   If not, once I install it I'll make a PR.

**Comment by SimonMellerin** [comment]
yep should work with any problem, let's try

**Comment by tacman** [comment]
There's an issue with php 8.3, but I'll submit a PR in a few minutes.

**Pull request merged**
